### ISSUE TITLE
About device

### ISSUE THREAD

**Issue by BIT-MJY** [stevenlsw/hoi-forecast#13]
Hello @stevenlsw ,

Thanks for sharing your nice work! Could you please post your device setup for training and evaluation (e.g. what GPU and how many) ?

**Comment by stevenlsw** [comment]
Hi, if you use the pre-extracted features from rulstm without training the backbone, it should be same requirements as [RULSTM](https://github.com/fpv-iplab/rulstm)

**Comment by BIT-MJY** [comment]
Thanks for the reply!
