### ISSUE TITLE
file for EGTEA Gaze+ dataset similar to ek100_eval_labels.pkl

### ISSUE THREAD

**Issue by BIT-MJY** [stevenlsw/hoi-forecast#14]
Hi @stevenlsw ,

Thanks for your fantastic work again! Could you tell me where is the ground-truth annotation file (containing such as 'norm_contacts') in EGTEA Gaze+ dataset similar to the `ek100_eval_labels.pkl` in EK-100 dataset?

Looking forward to your reply~

**Comment by stevenlsw** [comment]
Hi, thanks for your interest in our work. The evaluation labels could be found [here](https://drive.google.com/drive/folders/1ZcLYHormxgVzyiaQAid2Fz05O2o4xlH8?usp=drive_link).

**Comment by BIT-MJY** [comment]
many thanks to you and your pioneer work !!
