### ISSUE TITLE
Inquire about the license for copyright issue

### ISSUE THREAD

**Issue by Cogito2012** [stevenlsw/hoi-forecast#7]
Hi Shaowei,

Many thanks for sharing this great work! I noticed there is no LICENSE under this repo. I would like to use some pieces of your code, primarily the basic Transformer components from [networks/embedding.py](https://github.com/stevenlsw/hoi-forecast/blob/master/networks/embedding.py), [networks/layer.py](https://github.com/stevenlsw/hoi-forecast/blob/master/networks/layer.py), [networks/net_utils.py](https://github.com/stevenlsw/hoi-forecast/blob/master/networks/net_utils.py), and [networks/transformer.py](https://github.com/stevenlsw/hoi-forecast/blob/master/networks/transformer.py). 

To respect and protect your copyright, I'm wondering if these codes are developed by yourself or referred to some licensed open-source softwares (e.g., PyTorch, huggingface, etc). If developed by yourself, would you mind providing a license (MIT, BSD 3.0, or Apache 2.0)? If modified from other sources, could you tell where are they originally from?

Thank you!

**Comment by stevenlsw** [comment]
Hi, 

The code is originally borrowed from [attention is all you need](https://github.com/jadore801120/attention-is-all-you-need-pytorch) and then developed by me. The original repo is under MIT license. Hope that helps.

**Comment by Cogito2012** [comment]
@stevenlsw Thanks for pointing out the origin of the code. 
I checked the difference between your implementation and the link you provided, I found the modification is substantial. Since I'm primarily using your implementation, I cannot directly extend their MIT license to my code. In this case, could you please provide a license in this repo? Sorry for troubling you here :)
