### ISSUE TITLE
Inquiry `.lmdb` File for EGTEA Gaze+ Dataset

### ISSUE THREAD

**Issue by yayuanli** [stevenlsw/hoi-forecast#8]
Hi Steven,

Thank you so much for sharing the implementation of this interesting paper. 

If it's not too much trouble and if you still have the lmdb file of EGTEA Gaze+ Dataset on your local system, could you consider sharing it? This will immensely aid my progress and save me a big amount of time.

Thank you in advance.

**Comment by stevenlsw** [comment]
Hi yayuan, 

Thanks for your interest. Here is the [preprocessed code and pre-trained model for EGTEA  GAZE+ dataset](https://uofi.box.com/s/k90rl0cykvhjtbxvb7kzlultwvcbiaad), the feature extractor is trained on split 1 follow previous work setting. You could [extract hand-object bboxes](https://github.com/epic-kitchens/epic-kitchens-100-hand-object-bboxes) as pickle files and use the provided code to extract corresponding features. Hope that helps.

**Comment by yayuanli** [comment]
Hi Steven,

Greatly appreciated. It is really helpful!
